### ISSUE TITLE
macOS Monterey uses Port 7000

### ISSUE THREAD

**Issue by jobara** [GPII/gpii-testem#30]
## Describe the bug

The `fluid.testem.base` grade uses Port 7000 as the default for the [`coveragePort`](https://github.com/fluid-project/fluid-testem/blob/9f909808ad3aba9acc3dfc43102a372f67436103/src/js/testem-component.js#L364). In macOS 12 (Monterey) that port is used by Control Centre for the AirPlay feature ( see: https://developer.apple.com/forums/thread/682332 ). This is causing the test to error out because the port is already in use.

```log
08:11:21.736:  FATAL ERROR: Uncaught exception: listen EADDRINUSE: address already in use :::7000
Error: listen EADDRINUSE: address already in use :::7000
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at Function.listen (/Users/jo/Documents/git/infusion/node_modules/express/lib/application.js:618:24)
    at fluid.express.startServer (/Users/jo/Documents/git/infusion/node_modules/fluid-express/src/js/express.js:48:32)
    at togo (/Users/jo/Documents/git/infusion/src/framework/core/js/FluidIoC.js:2844:33)
    at fluid.event.firer.fire (/Users/jo/Documents/git/infusion/src/framework/core/js/Fluid.js:1775:40)
    at fluid.express.routable.connectDirectDescendants (/Users/jo/Documents/git/infusion/node_modules/fluid-express/src/js/routable.js:70:37)
    at togo (/Users/jo/Documents/git/infusion/src/framework/core/js/FluidIoC.js:2844:33)
    at fluid.event.firer.fire (/Users/jo/Documents/git/infusion/src/framework/core/js/Fluid.js:1775:40)
    at fluid.express.init (/Users/jo/Documents/git/infusion/node_modules/fluid-express/src/js/express.js:43:43)
    at togo (/Users/jo/Documents/git/infusion/src/framework/core/js/FluidIoC.js:2844:33)
    at fluid.event.firer.fire (/Users/jo/Documents/git/infusion/src/framework/core/js/Fluid.js:1775:40)
    at fluid.concludeComponentInit (/Users/jo/Documents/git/infusion/src/framework/core/js/FluidIoC.js:1532:30)
    at /Users/jo/Documents/git/infusion/src/framework/core/js/FluidIoC.js:2203:29
    at Array.forEach (<anonymous>)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! infusion@4.0.0 test:browser: `testem ci --file tests/testem.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the infusion@4.0.0 test:browser script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jo/.npm/_logs/2021-10-27T12_11_21_756Z-debug.log
ERROR: "test:browser" exited with 1.
npm ERR! Test failed.  See above for more details.
```
### Desktop
 - OS: macOS 12 (Monterey)

**Comment by the-t-in-rtf** [comment]
I looked into this for a bit based on the get-port package we chatted about yesterday.  Unfortunately [Node's "net" module uses asynchronous functions](https://nodejs.org/api/net.html#netcreateconnectionport-host-connectlistener) that don't have a synchronous equivalent.

I might be able to work with this, but I'd have to do a lot more work that I think I can manage at the moment.  To get a valid port, I'd either have to scan all ports every time (which would slow things down), or I'd have to figure out a new promise chaining mechanism that stops when the first port is found.

Assuming I could do tame the async calls without adding too many ES6-isms to the codebase, I'd have to set up some kind of `createOnEvent` setup for most components, which from past experience tends to lead to hanging tests on startup if you aren't very careful with the implementation details.

For now, it seems most appropriate to simply update the port to a non-conflicting value.
